### ISSUE TITLE
Maven Repository for release versions

### ISSUE THREAD

**Issue by akshayjain3450** [opensearch-project/opensearch-hadoop#105]
Generally, I pick any connectors available from maven and keep a tab on the latest versions, which is very handy. Are there any indexes available from where we can pick the build and import them in our SBT or Gradle Projects? Or is the creation of the maven repository for this on the road map?

**Comment by wbeckler** [comment]
We will release a built jar on maven after we do a security review, which is ongoing.

**Comment by akshayjain3450** [comment]
@wbeckler is there any timeline to this as in when can we expect the release.?

**Comment by wbeckler** [comment]
The review started a week ago, and they usually take 4-6 weeks but there are no guarantees, and no dates have been offered by the reviewers.

**Comment by harshavamsi** [comment]
Dup of #134
