### ISSUE TITLE
Opensearch hadoop jar doesn't work for Opensearch 1.2.3 version

### ISSUE THREAD

**Issue by manirudh78** [opensearch-project/opensearch-hadoop#108]
### What is the bug?
opensearch-hadoop.jar is not supporting the Opensearch version 1.2.3

### How can one reproduce the bug?
Try using scala spark to connect with opensearch version 1.2.3

import org.apache.spark.sql.SparkSession
import org.opensearch.spark.sql._
//import org.opensearch.spark._

object ScalaSparkTestApp extends App {

  val spark = SparkSession.builder().master("local[*]")
    .config("spark.jars", "jar/opensearch-hadoop-3.0.0-SNAPSHOT.jar")
    .config("opensearch.nodes", "127.0.0.1")
    .config("opensearch.port", "9200")
    .config("opensearch.net.http.auth.user", "admin")
    .config("opensearch.net.http.auth.pass", "admin")
    .config("opensearch.net.ssl", "true")
    .config("opensearch.net.ssl.cert.allow.self.signed", "true")
    .config("opensearch.batch.size.bytes", "1kb")
    .config("opensearch.nodes.wan.only", "true")
//    .config("opensearch.batch.write.retry.count", "9")
//    .config("opensearch.http.retries", "9")
//    .config("opensearch.http.timeout", "18000")
    .getOrCreate()

  // write to opensearch

  var df = spark.read.option("multiline","true").json("resources/test.json")

  df.saveToOpenSearch("test_scala_write")
  

}

### What is the expected behavior?
It should have written the data to the opensearch index

### What is your host/environment?
_Operating system, version._

### Do you have any screenshots?
_If applicable, add screenshots to help explain your problem._

### Do you have any additional context?
_Add any other context about the problem._

**Comment by harshavamsi** [comment]
Can you try building from the [1.0 branch](https://github.com/opensearch-project/opensearch-hadoop/tree/1.0) and then running against 1.2.3?
