### ISSUE TITLE
[FEATURE] Hadoop Client

### ISSUE THREAD

**Issue by brijos** [opensearch-project/opensearch-hadoop#134]
**Is your feature request related to a problem?**
When using Elastic Search in the past, some in the [community](https://forum.opensearch.org/t/opensearch-hadoop-apache-spark-elasticsearch-connector/7730/3) had been used to connecting using a Hadoop client. The ask is to create a Hadoop client which will connect to OpenSearch.

**Comment by prashantsc** [comment]
Thanks @harshavamsi  and @wbeckler. Would like to know if we have any development on ETA in last two weeks?

**Comment by harshavamsi** [comment]
@prashantsc the client is ongoing security review inside of Amazon. We are targeting 4/30/23 currently, but it could change depending on outcomes.

**Comment by prashantsc** [comment]
Thanks @harshavamsi  for the information.

**Comment by junhl** [comment]
@harshavamsi do you have updates on the security review ? We passed 4/30/23 so wondering if a new date is to be set.

**Comment by harshavamsi** [comment]
@junhl Thanks for checking in. Happy to report that the security review is complete and we're now working towards a release. There is some ongoing discussion over at https://github.com/opensearch-project/opensearch-build/issues/3385 about the nuances of releasing this client. That is also where we will track the release. Stay tuned this week where most likely a release is going to happen. Thank for being patient!

**Comment by chaitujil** [comment]
Spark 3.x clusters can't connect to Opensearch using elasticsearch-spark libraries. Somehow the compatibility is broken and the connection fails with

```org.elasticsearch.hadoop.EsHadoopIllegalArgumentException: Cannot detect ES version```

However Spark 2.x clusters don't have this problem. Blocker for us because we only have Spark 3.x clusters :(

Is this client coming anytime soon?

**Comment by harshavamsi** [comment]
Hi @chaitujil the OpenSearch build team is working on getting a release out as soon as possible. In the meanwhile could you let me know if you're using Managed OpenSearch on AWS or if you're hosting your own service. Also, can I know what versions of OpenSearch you're targetting? Thanks.

**Comment by chaitujil** [comment]
We are targeting OS 1.1 cluster. Managed OpenSearch.

**Comment by harshavamsi** [comment]
Hi folks, we published Snapshots here -- https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/. Do give it a try and let us know. We're going to publish an actual release early this week. Thanks!

**Comment by mgolatkar** [comment]
@harshavamsi It looks like the opensearch-spark libs shared at the link above https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/ work with Amazon OpenSearch Service with OpenSearch engine v2.3. We want to connect to Amazon OpenSearch Service with Elasticsearch engine v7.10 in the AWS Glue Job (Type: Spark, Glue version - 3.0 or 4.0) . Can you please share the version of the libraries/jar files that we need to use for the same?

**Comment by harshavamsi** [comment]
> @harshavamsi It looks like the opensearch-spark libs shared at the link above https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/ work with Amazon OpenSearch Service with OpenSearch engine v2.3. We want to connect to Amazon OpenSearch Service with Elasticsearch engine v7.10 in the AWS Glue Job (Type: Spark, Glue version - 3.0 or 4.0) . Can you please share the version of the libraries/jar files that we need to use for the same?

Hi, we have a workaround that supports ES 7.x clusters. Have you given the connector a try? Does it fail?

**Comment by prashantsc** [comment]
Hi Harsha

We want to go away from the AWS Marketplace connector (and open source
ElasticSearch Hadoop library)  which has security issues such as it needs
wide open permissions/policies.

1. With the latest updates we are good with use case # 1.
2. We need to use  ElasticSearch Hadoop library if there is no other way
with opensearch hadoop library that uses an Assume role.

Regards,
Prashant

**Comment by indranilr** [comment]
> Hi folks, we published Snapshots here -- https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/. Do give it a try and let us know. We're going to publish an actual release early this week. Thanks!

Is this release compatible with Open Search 1.2.x and Spark 3.2.x / Scala 2.12 ?

**Comment by mgolatkar** [comment]
> > @harshavamsi It looks like the opensearch-spark libs shared at the link above https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/client/ work with Amazon OpenSearch Service with OpenSearch engine v2.3. We want to connect to Amazon OpenSearch Service with Elasticsearch engine v7.10 in the AWS Glue Job (Type: Spark, Glue version - 3.0 or 4.0) . Can you please share the version of the libraries/jar files that we need to use for the same?
> 
> Hi, we have a workaround that supports ES 7.x clusters. Have you given the connector a try? Does it fail?

@harshavamsi On referencing the jar file opensearch-spark-30_2.13-1.0.0-20230513.002822-1.jar in our AWS Glue Job (Type: Spark, Glue version - 3.0 or 4.0) we get the following error:

Scala signature package has wrong version expected: 5.0 found: 5.2 in package.class

Does this jar have to be compiled with java 8? Can you please help take a look at the issue?

**Comment by akshayjain3450** [comment]
Hi @harshavamsi , is there a place wherein I can get all the configuration/options supported by Open search through spark?
This helps me in my project to allow users to define these as per the requirement and need.

Using, OpenSearch 1.3.10 with Spark 3.3.1 with Scala 2.12.

**Comment by harshavamsi** [comment]
@akshayjain3450 please refer to this file -- https://github.com/opensearch-project/opensearch-hadoop/blob/main/mr/src/main/java/org/opensearch/hadoop/cfg/ConfigurationOptions.java. It has all the configuration options that you can set within the client. Thanks!

**Comment by harshavamsi** [comment]
Closing this issue as completed via #227

**Comment by venkatbrr** [comment]
@harshavamsi I don't see workflow for scala 2.12 version. are not publishing any jar for Spark 3.x and Scala 2.12 compatable versions?
https://github.com/opensearch-project/opensearch-hadoop/tree/main/.github/workflows

**Comment by Xtansia** [comment]
> @harshavamsi I don't see workflow for scala 2.12 version. are not publishing any jar for Spark 3.x and Scala 2.12 compatable versions?
> https://github.com/opensearch-project/opensearch-hadoop/tree/main/.github/workflows

@venkatbrr The artifact you're looking for is published as  [`org.opensearch.client/opensearch-spark-30_2.12`](https://central.sonatype.com/artifact/org.opensearch.client/opensearch-spark-30_2.12)

**Comment by venkatbrr** [comment]
@harshavamsi @Xtansia Can you please update the compatability section for 1.0.1 version? we are trying to use Hadoop client for AWS Opensearch managed cluster of 2.5 version.
https://github.com/opensearch-project/opensearch-hadoop/blob/main/COMPATIBILITY.md
