### ISSUE TITLE
[FEATURE] Combine support for ES, OS 1.x, 2.x, 3.x into a single branch

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-hadoop#183]
### Is your feature request related to a problem?
Given that there isn't a lot of development being done on this repository for older versions of OS, there is a lot of maintenance overhead to have to maintain the various branches. I propose that we glue the various versions into a single code base.

**Comment by dblock** [comment]
Can you do this via moving to opensearch-java #124?

**Comment by harshavamsi** [comment]
@dblock yes, moving the rest layer to opensearch-java does help, for the purposes of the initial release we're going to continue using the existing rest layer. But switching over to opensearch-java should solve the problem in the longer term.

**Comment by harshavamsi** [comment]
Closing via #199
