### ISSUE TITLE
[Bug]: gradle says java 11 is required but documentation says java8 or higher

### ISSUE THREAD

**Issue by chaitujil** [opensearch-project/opensearch-hadoop#216]
### Describe the bug

I tried to build the source with jdk1.8 and gradle build failed with this below error

```> At least Java 11 is required to use opensearch gradle tools```

### To reproduce

`./gradlew`

### Expected behavior

Builds with jdk1.8 or update the documentation

### Host / Environment

macOS

**Comment by harshavamsi** [comment]
Hi, the minimum required version for the build is Java 11. We're going to update the documentation soon.

**Comment by himgang** [comment]
@harshavamsi except for the build part. Will the library work fine with Java 8 or we have dropped support for it ?

**Comment by harshavamsi** [comment]
@himgang it will work with Java 8.
