### ISSUE TITLE
[BUG] Most recent opensearch-spark jar causing errors in glue job

### ISSUE THREAD

**Issue by enano9311** [opensearch-project/opensearch-hadoop#243]
### What is the bug?
in [Issue 28](https://github.com/opensearch-project/opensearch-hadoop/issues/28) it was mentioned that “SigV4 has been backported and should work.“.

I am now trying to use Glue 4.0 (Spark 3.3.0) to connect to an Opensearch 1.3 (or ES 7.x) cluster with the `opensearch-spark-30_2.12-1.0.0.jar` jar downloaded from the [Github Releases Page under tag v1.0.0](https://github.com/opensearch-project/opensearch-hadoop/releases/tag/v1.0.0).

However we are now running into this issue:
```
An error occurred while calling o106.load. org.apache.spark.sql.sources.DataSourceRegister: Provider org.opensearch.spark.sql.DefaultSource15 could not be instantiated
```

What is the correct jar file to use to connect Spark 3.3 to Opensearch 1.3 (or ES 7.x) with IAM role based authentication?

### How can one reproduce the bug?
- Create a Glue job using Glue 4.0 and the `opensearch-spark-30_2.12-1.0.0.jar`
- Run `spark.read.load(<path-to-some-parquet>)`

### What is the expected behavior?
- Glue job should be able to read load data from s3 without failing
- Glue job should be able to write data to Opensearch 1.3 cluster without failing

### What is your host/environment?
Glue 4.0 (Spark 3.3.0) to connect to an Opensearch 1.3 (or ES 7.x) cluster with the `opensearch-spark-30_2.12-1.0.0.jar` jar

### Do you have any screenshots?
N/A

### Do you have any additional context?
This job was previously working with IP-based authentication and the `elasticsearch-spark-30_2.12-7.13.1.jar` jar using Glue 3.0 and Glue 4.0, updating to the new jar from the [Github Releases Page under tag v1.0.0](https://github.com/opensearch-project/opensearch-hadoop/releases/tag/v1.0.0) causes failures.

**Comment by harshavamsi** [comment]
Hi, 

Can you please also share your spark conf. I'd like to see the conf variables.

**Comment by enano9311** [comment]
```
spark.sql.extensions=io.delta.sql.DeltaSparkSessionExtension --conf spark.sql.catalog.spark_catalog=org.apache.spark.sql.delta.catalog.DeltaCatalog  --conf spark.executor.memoryOverhead=2g --conf spark.driver.memoryOverhead=2g --conf spark.driver.maxResultSize=16g --conf spark.sql.broadcastTimeout=7200 --conf spark.executor.heartbeatInterval=20s --conf spark.sql.shuffle.partitions=128 --conf spark.shuffle.compress=true --conf spark.rdd.compress=true
```

**Comment by harshavamsi** [comment]
Thanks, where and how do you reference the JAR?

**Comment by enano9311** [comment]
Under Glue > Job Details > Libraries > Python Library Path/Dependent JARs path:

```
s3://<my-jars-bucket>/delta-core_2.12-2.2.0.jar,\
s3://<my-jars-bucket>/delta-storage-2.2.0.jar,\
s3://<my-jars-bucket>/opensearch-spark-30_2.13-1.0.0.jar
```

**Comment by enano9311** [comment]
I tried with both 2.12 and 2.13 and both returned the same 
```
An error occurred while calling o106.load. org.apache.spark.sql.sources.DataSourceRegister: Provider org.opensearch.spark.sql.DefaultSource15 could not be instantiated
```

error

**Comment by enano9311** [comment]
Mitigation ended up being:

1. Using the fixed `opensearch-spark` jar that includes the [3p imports fix](https://github.com/opensearch-project/opensearch-hadoop/pull/245).
2. Including the `aws-java-sdk-bundle` jar in my glue job. Downloaded [here](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bundle)
3. Using the options recommended in [this documentation](https://github.com/opensearch-project/opensearch-hadoop#signing-requests-for-iam-authentication-2). Specifically I had to set the following write options:
```
{
    "pushdown": "true",
    "opensearch.nodes": "myopensearch-domain-endpoint.es.amazonaws.com",
    "opensearch.port": "443",
    "opensearch.nodes.resolve.hostname": "false",
    "opensearch.nodes.wan.only": "true",
    "opensearch.net.ssl" : "true",
    "opensearch.resource": "my-es-index",
    "opensearch.aws.sigv4.enabled": "true",
    "opensearch.aws.sigv4.region": "us-west-2",
}
```
6. Making sure the IAM role associated with the glue job had the `AmazonOpenSearchServiceFullAccess` policy
7. Ensuring the Opensearch cluster access policy grants `es:*` on both the domain itself and sub-resources
```
{
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::acct-id:role/Glue-Role"
      },
      "Action": "es:*",
      "Resource": [
        "arn:aws:es:us-west-2:acct-id:domain/cluster-name",
        "arn:aws:es:us-west-2:acct-id:domain/cluster-name/*"
      ]
    }
```

**Comment by wbeckler** [comment]
@enano9311 Your summary is awesome!!! Thank you!!!!!
