### ISSUE TITLE
Missing MAINTAINERS.md file

### ISSUE THREAD

**Issue by krisfreedain** [opensearch-project/opensearch-hadoop#25]
During an evaluation of our repos, we noticed this repository does not contain a MAINTAINERS.md file. Our https://github.com/opensearch-project/.github/blob/main/MAINTAINERS.md file provides an overview and outline to resolve this.

**Comment by wbeckler** [comment]
This is getting addressed here: https://github.com/opensearch-project/opensearch-hadoop/pull/23
