### ISSUE TITLE
[BUG] strict parameter not honored in SparkSqlScalaSuite

### ISSUE THREAD

**Issue by nknize** [opensearch-project/opensearch-hadoop#41]
### What is the bug?
`translateFilter` accepst a `strictPushDown` parameter to request using filters that exactly match the given values. This parameter is not honored and leads to failing tests in `SparkSQLScalaSuite`.

### How can one reproduce the bug?
```./gradlew ':opensearch-spark-20:integrationTest' --tests "org.opensearch.spark.integration.SparkSQLScalaSuite" --info```

### What is the expected behavior?
passing tests

**Comment by nknize** [comment]
Turns out this is an [upstream bug](https://github.com/opensearch-project/OpenSearch/issues/5461) in WildcardQuery where `case_insensitive` has no effect on default analyzed fields. 

I've opened an [upstream PR](https://github.com/opensearch-project/OpenSearch/pull/5462) to fix the issue.

**Comment by harshavamsi** [comment]
Closing via #125
