### ISSUE TITLE
[FEATURE] Set opensearch-hadoop 2.0.0 baseline JDK version to JDK-21

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-hadoop#472]
### Is your feature request related to a problem? Please describe

Set `opensearch-hadoop` 2.0.0 baseline JDK version to JDK-21

### Describe the solution you'd like

See please https://github.com/opensearch-project/OpenSearch/issues/10745

### Related component

Build

### Describe alternatives you've considered

N/A

### Additional context

See please https://github.com/opensearch-project/OpenSearch/issues/14011

**Comment by Xtansia** [comment]
@reta Are you sure this applies here? As this is a client shouldn't it be in the same boat as the Java client and trying to preserve as much backwards compatibility as possible?

**Comment by reta** [comment]
> @reta Are you sure this applies here? As this is a client shouldn't it be in the same boat as the Java client and trying to preserve as much backwards compatibility as possible?

Thanks @Xtansia , I am pretty sure it does apply )sadly) unless there is no goal to support Apache Lucene 10 by `opensearch-hadoop` [1], the baseline comes from there.

[1] https://github.com/opensearch-project/opensearch-hadoop/blob/main/buildSrc/opensearch-hadoop-version.properties#L3

**Comment by Xtansia** [comment]
@reta I believe those might only used for integration tests, but would need to confirm

**Comment by dblock** [comment]
[Catch All Triage - Attendees [1](https://github.com/dblock/), [2](https://github.com/krisfreedain), [3](https://github.com/andrross), [4](https://github.com/gkamat), [5](https://github.com/getsaurabh02)]

**Comment by msfroh** [comment]
I searched for `org.apache.lucene` to see if there are any imports: https://github.com/search?q=repo%3Aopensearch-project%2Fopensearch-hadoop%20org.apache.lucene&type=code

It doesn't look like it.
