### ISSUE TITLE
PySpark write dataframe to OpenSearch

### ISSUE THREAD

**Issue by manirudh78** [opensearch-project/opensearch-hadoop#76]
Hello,

Hope you are keeping well.

**Are there any plans or ongoing development for pyspark write to OpenSearch?**

Any hints or responses are highly appreciated.

Thanks.
Have a wonder day.

**Comment by wbeckler** [comment]
Have you looked at https://notebook.community/Cyb3rWard0g/HELK/docker/helk-jupyter/notebooks/tutorials/05-Intro_pyspark_sparkSQL_sysmon

opensearch-hadoop is very new and hasn't been tested with pyspark, but it's worth a try to do the above but with opensearch in place of elasticsearch.
