### ISSUE TITLE
[RFC] Support for OpenSearch and ElasticSearch

### ISSUE THREAD

**Issue by harshavamsi** [opensearch-project/opensearch-hadoop#81]
### What are you proposing?
Currently the main branch of the hadoop client is set up to work with the unreleased `3.0` version of [OpenSearch](https://github.com/opensearch-project/OpenSearch). There has been a lot of community feedback and asks around support for >=ElasticSearch 7.10, OpenSearch 1.x, and OpenSearch 2.x. This poses an interesting problem since a lot of the work we've done for this client so far has been to predominantly support OpenSearch.

### What users have asked for this feature?
There has been a lot of internal amazon customers and community requesting that we support both OpenSearch and ElasticSearch. 

### What problems are you trying to solve?
Given that we currently have only support for OpenSearch, I propose that we add support for ElasticSearch on the 7.x branch.

### Proposed Solution
Currently looking at three possible approaches:
- Support both ElasticSearch and OpenSearch on the 1.x line, and support only OpenSearch going forward in the 2.x line
- Support ElasticSearch only exclusively on the 7.x line with features like #48 back-ported
- Only support OpenSearch 1.x and 2.x

**Comment by AlJohri** [comment]
My team is currently tied to Elasticsearch 7.10 so we would be comfortable with either of the first two proposals ("Support both ElasticSearch and OpenSearch on the 1.x line..." or "Support ElasticSearch only exclusively on the 7.x line...").

When/if we upgrade from ES 7.10, I don't see strong reasons why we would not be able to upgrade directly to the latest Opensearch. Therefore, I think "Support ElasticSearch only exclusively on the 7.x" in addition to supporting Opensearch 3.0 on `main` is sufficient for our purposes.

**Comment by subbaray** [comment]
+1

**Comment by enano9311** [comment]
+1

**Comment by nknize** [comment]
> Support both ElasticSearch and OpenSearch on the 1.x line, and support only OpenSearch going forward in the 2.x line

This was the original intent when I started refactoring the forked codebase to OpenSearch. Elasticsearch and OpenSearch 1.x compatibility was punted for a few reasons we'll need to hash out if we collectively determine this is a huge community need (vs supporting only OpenSearch 2.0+):

1. Juggling the `mainResponse` version parsing between `ESMajorVersion` and [OpenSearchMajorVersion](https://github.com/opensearch-project/opensearch-hadoop/blob/main/mr/src/main/java/org/opensearch/hadoop/util/OpenSearchMajorVersion.java). I achieved this in OpenSearch core by [spoofing the version in main response](https://github.com/opensearch-project/OpenSearch/pull/708), which Elastic quickly [took other measures to prevent in 7.15+](https://github.com/elastic/elasticsearch-py/commit/801a8390937a6ef909158c87a6a2e0e39300dcfa).
2. What are the library expectations? The current implementation refactored all `Es*` classes to `OpenSearch`, essentially clipping Elasticsearch support and leveraging those old `EsRDD` logic to only talk to OpenSearch but under a proper `OpenSearch` namespace. I don't think it makes sense to have instances of `OpenSearchRDD` (or `OpenSearchRow` for that matter) serve as a data frame to an ES cluster as that's a confusing and misleading experience. OTH, it's a lot of code to juggle the `ESRDD` logic alongside the `OpenSearchRDD`.  Sure we could create common Base class implementations, but refactoring that just for ES 7.10 and OpenSearch 1.x support when the core has moved toward 2.5 release and soon planning an OpenSearch 3.0 release is a lot of effort for `¯\_(ツ)_/¯` benefit?
3. OpenSearch 1.x support was neutered only for convenience of removing bwc support for `types` (which are [removed in OpenSearch 2.0+](https://github.com/opensearch-project/OpenSearch/pulls?q=is%3Apr+%22type+removal%22+is%3Aclosed+)). If we want to support OpenSearch 1.0+ we'd have to bring back bwc logic for the types API.

The current implementation is designed to support OpenSearch 2.x+ (build.gradle has 3.0.0 just to match version w/ OpenSearch main branch), but the bwc testing infra isn't fully there. Maybe that's where we put effort? Make sure 2.x testing is solid such that the connector is comprehensively tested w/ an OpenSearch 2.x Fixture moving forward?

**Comment by harshavamsi** [comment]
Initial support for OpenSearch 1.x and ES 7.10 has been merged into the `1.0` branch.

**Comment by manirudh78** [comment]
Hello @nknize , @harshavamsi 
Hope you are keeping well. 
I have opened an issue https://github.com/opensearch-project/opensearch-hadoop/issues/80 where i tried to build the scala jar from the main branch and used it to test spark to opensearch 2.5.0 connection it doesn't work. With your above changes does it fixes that issue? Please refer to the issue link for more details on replicating the issue.

Thanks, looking forward for your response.
